apiVersion: ingest.opensearch.m.upbound.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    meta.upbound.io/example-id: ingest/v1alpha1/pipeline
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    body: |
      {
        "description" : "describe pipeline",
        "version": 123,
        "processors" : [
          {
            "set" : {
              "field": "foo",
              "value": "bar"
            }
          }
        ]
      }
    name: terraform-test
